version: '2'
services:
    shoe-mongodb:
        container_name: shoe-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/shoe/mongodb/:/data/db/
