version: '2'
services:
    shoe-mongodb:
        container_name: shoe-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        command: mongos --configdb shoe-mongodb-config
    shoe-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    shoe-mongodb-config:
        image: mongo:3.2.3
        container_name: shoe-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
